on:
  pull_request:
    types:
    - closed

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ github.event.pull_request.merged != true }}
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const workflowIds = [
            '.github/workflows/ci.yml'
          ];

          for (const workflowId of workflowIds) {
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              per_page: 100,
              event: 'pull_request',
              branch: context.payload.pull_request.head.ref,
            });

            const activeRuns = workflowRuns.data.workflow_runs.filter((workflowRun) => {
              return workflowRun.status === 'queued' || workflowRun.status === 'in_progress';
            });

            console.log(`${context.payload.pull_request.html_url} ${workflowId}`);

            for (const activeRun of activeRuns) {
              await github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: activeRun.id,
              });
            }
          }
